"""Add document_type to documents

Revision ID: 728fb37830a5
Revises: 3fca9fac2218
Create Date: 2026-06-15 14:30:25.968256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728fb37830a5'
down_revision: Union[str, Sequence[str], None] = '3fca9fac2218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
