"""Add drive_tokens table

Revision ID: 9b1cc25264c8
Revises: 728fb37830a5
Create Date: 2026-06-15 15:00:37.577909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1cc25264c8'
down_revision: Union[str, Sequence[str], None] = '728fb37830a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_tokens_id'), 'drive_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_drive_tokens_user_id'), 'drive_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drive_tokens_user_id'), table_name='drive_tokens')
    op.drop_index(op.f('ix_drive_tokens_id'), table_name='drive_tokens')
    op.drop_table('drive_tokens')
    # ### end Alembic commands ###
